- name: Pull and run docker image
  hosts: localhost
  tasks:

    - name: pull docker image
      shell: docker pull supreethv/spe_miniproject:latest

    - name: run container
      shell: docker run -i -t --name spe_miniproject -d supreethv/spe_miniproject